/** Compiled Worker integration tests. Identities and data exist only in isolated in-memory D1/R2. */
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir} from 'node:fs/promises';
import path from 'node:path';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=wranglerRequire('miniflare');
const root=path.resolve('dist/server');
const files=await readdir(root,{recursive:true});
const modules=['index.js',...files.filter(f=>/\.(m?js)$/.test(f)&&f!=='index.js')].map(f=>({type:'ESModule',path:path.join(root,f)}));
const mf=new Miniflare({modules,modulesRoot:root,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'city-guide-test'},r2Buckets:{BUCKET:'city-guide-test'}});
let checks=0;
function check(value,message){assert.ok(value,message);checks++;console.log('PASS '+message)}
const headers=who=>who?{'oai-authenticated-user-id':who,'oai-authenticated-user-email':who==='qa-owner'?'nncdecdgc@gmail.com':who+'@example.test'}:{};
async function request(url,who='qa-owner',body){const r=await mf.dispatchFetch('http://local.test'+url,{method:body?'POST':'GET',headers:{...headers(who),...(body?{'Content-Type':'application/json','Origin':'http://local.test'}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();return {status:r.status,...d}}
const action=(action,data,who='qa-owner',surface)=>request('/api/action',who,{action,data,...(surface?{surface}:{})});
try{
 const database=await mf.getD1Database('DB');
 for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const stmt of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(stmt.trim())await database.prepare(stmt).run();
 check((await request('/api/state',null)).status===401,'anonymous data access is rejected');
 const first=await request('/api/state?surface=admin');
 check(first.status===200&&first.user.role==='admin'&&first.venues.length===9,'allowlisted administrator initializes nine demo places');
 const newcomer=await request('/api/state','qa-partner');check(newcomer.user.role==='tourist','new accounts default to the tourist role');
 check((await request('/api/state?surface=admin','qa-partner')).status===403&&(await request('/api/state?surface=partner','qa-partner')).status===403,'tourists cannot read either management area');
 check((await action('userRole',{id:'qa-partner',role:'partner',expectedRole:'tourist'},'qa-owner','admin')).status===200,'administrator can assign a business role');
 const partner=await request('/api/state?surface=partner','qa-partner');check(partner.user.role==='partner'&&!partner.users,'business role persists without a user directory');
 check((await action('userRole',{id:'qa-partner',role:'tourist',expectedRole:'tourist'})).status===409,'stale role changes are rejected');
 check((await action('userRole',{id:'qa-owner',role:'tourist',expectedRole:'tourist'})).status===409,'the project owner role is locked');
 const tourist=await request('/api/state?surface=tourist','qa-tourist');check(tourist.user.role==='tourist'&&!tourist.users,'tourist state has no user directory');
 const draft={...first.venues[0],id:undefined,name:'QA restaurant',status:'draft',version:0};
 const created=await action('saveVenue',draft);check(created.status===200,'owner can save a draft');
 const id=created.result.id;let saved=created.state.venues.find(v=>v.id===id);
 check(!(await request('/api/state','qa-partner')).venues.some(v=>v.id===id),'private draft is hidden from another business');
 check(!(await request('/api/state?surface=tourist')).venues.some(v=>v.id===id),'owner traveler preview also excludes private drafts');
 check((await action('saveVenue',{...saved,name:'forbidden change'},'qa-partner')).status===403,'another business cannot change the owner listing');
 check((await action('saveVenue',draft,'qa-tourist')).status===403,'tourists cannot create listings');
 check((await action('saveVenue',{...saved,version:0})).status===409,'stale listing edits are rejected');
 const published=await action('saveVenue',{...saved,status:'published'});saved=published.state.venues.find(v=>v.id===id);
 check((await request('/api/state')).venues.find(v=>v.id===id).status==='published','listing changes survive a fresh API read');
 const providerListing=await action('saveVenue',{...draft,name:'QA business listing',status:'published'},'qa-partner','partner');
 let owned=providerListing.state.venues.find(v=>v.id===providerListing.result.id);
 check(owned.status==='pending'&&owned.ownerId==='qa-partner','business publication requires administrator approval');
 check((await action('venueStatus',{id:owned.id,status:'published',version:owned.version},'qa-partner')).status===403,'businesses cannot approve their own publication');
 const approved=await action('venueStatus',{id:owned.id,status:'published',version:owned.version});
 check(approved.status===200&&(await request('/api/state?surface=tourist','qa-tourist')).venues.some(v=>v.id===owned.id),'approval publishes the listing to tourists');
 check((await action('venueStatus',{id:owned.id,status:'draft',version:owned.version})).status===409,'listing moderation checks its version');
 const favorite=await action('favorite',{id,value:true},'qa-tourist','tourist');check(favorite.state.favorites.includes(id)&&!(await request('/api/state')).favorites.includes(id),'favorites are scoped per user');
 const future=new Date(Date.now()+7*86400000).toISOString().slice(0,10);const end=new Date(Date.now()+10*86400000).toISOString().slice(0,10);
 const base={name:'QA visitor',phone:'',date:future,endDate:end,time:'12:00',guests:1,payment:'demo',note:''};
 const ids=[crypto.randomUUID(),crypto.randomUUID()];
 const results=await Promise.all(ids.map(id=>action('book',{...base,id,venueId:'demo-rent'},'qa-partner')));
 check(results.filter(r=>r.status===200).length===1&&results.filter(r=>r.status===409).length===1,'overlapping requests cannot double-book the last vehicle');
 const booked=results.find(r=>r.status===200);const bid=booked.result.id;
 const repeat=await action('book',{...base,id:bid,venueId:'demo-rent'},'qa-partner');check(repeat.status===200&&repeat.state.bookings.filter(b=>b.id===bid).length===1,'retrying a booking is idempotent');
 const otherState=await request('/api/state?surface=tourist','qa-tourist');const ownerPreview=await request('/api/state?surface=tourist');
 check(!otherState.bookings.some(b=>b.id===bid)&&!ownerPreview.bookings.some(b=>b.id===bid),'tourist state never exposes other customers’ bookings');
 check((await action('bookingStatus',{id:bid,status:'confirmed'},'qa-partner')).status===403,'a customer cannot confirm the provider booking');
 check((await action('bookingStatus',{id:bid,status:'cancelled'},'qa-tourist')).status===403,'a tourist cannot cancel another customer’s booking');
 check((await action('review',{bookingId:bid,rating:5,text:'QA review'},'qa-partner')).status===400,'reviews require a completed booking');
 check((await action('bookingStatus',{id:bid,status:'confirmed'})).status===200,'administrator can confirm a pending request');
 check((await action('bookingStatus',{id:bid,status:'completed'})).status===200,'administrator can complete a confirmed request');
 const reviewed=await action('review',{bookingId:bid,rating:5,text:'QA completed visit'},'qa-partner');
 check(reviewed.status===200,'customer can review their completed test visit');
 const rid=reviewed.state.reviews.find(r=>r.bookingId===bid).id;
 check((await action('review',{bookingId:bid,rating:4,text:'duplicate review'},'qa-partner')).status===400,'duplicate reviews are rejected');
 const visibleReview=(await request('/api/state?surface=tourist','qa-tourist')).reviews.find(r=>r.id===rid);
 check(visibleReview&&visibleReview.userId===''&&visibleReview.bookingId==='','public review text conceals private account and booking identifiers');
 check((await action('moderateReview',{id:rid,version:1,status:'hidden'},'qa-tourist')).status===403,'tourists cannot moderate reviews');
 const hidden=await action('moderateReview',{id:rid,version:1,status:'hidden'});
 check(hidden.status===200&&!(await request('/api/state?surface=tourist','qa-tourist')).reviews.some(r=>r.id===rid)&&(await request('/api/state?surface=tourist','qa-partner')).reviews.some(r=>r.id===rid&&r.status==='hidden'),'hidden reviews remain in their author’s history only');
 check((await action('moderateReview',{id:rid,version:1,status:'published'})).status===409,'stale review moderation is rejected');
 const replied=await action('reviewReply',{id:rid,version:2,reply:'Thank you for the visit'});
 check(replied.status===200&&replied.state.reviews.find(r=>r.id===rid).reply==='Thank you for the visit','administrator reply is persisted');
 check((await action('moderateReview',{id:rid,version:3,status:'published'})).status===200&&(await request('/api/state?surface=tourist','qa-tourist')).reviews.find(r=>r.id===rid).reply==='Thank you for the visit','restored review includes its business reply');
 const ownBid=crypto.randomUUID();
 check((await action('book',{...base,id:ownBid,venueId:owned.id},'qa-tourist','tourist')).status===200,'tourist can book an approved business');
 check((await action('bookingStatus',{id:ownBid,status:'confirmed'},'qa-partner','partner')).status===200&&(await action('bookingStatus',{id:ownBid,status:'completed'},'qa-partner','partner')).status===200,'business can confirm and complete its own requests');
 const ownReviewed=await action('review',{bookingId:ownBid,rating:4,text:'QA business visit'},'qa-tourist','tourist');const ownReview=ownReviewed.state.reviews.find(r=>r.bookingId===ownBid);
 check((await action('reviewReply',{id:ownReview.id,version:1,reply:'Business reply'},'qa-partner','partner')).status===200,'business can reply to reviews of its listing');
 check((await action('reviewReply',{id:rid,version:4,reply:'Foreign reply'},'qa-partner','partner')).status===403,'business cannot reply to another listing’s review');
 const cancelId=crypto.randomUUID();await action('book',{...base,id:cancelId,venueId:owned.id},'qa-tourist','tourist');
 check((await action('bookingStatus',{id:cancelId,status:'cancelled'},'qa-tourist','tourist')).status===200,'tourist can cancel their own pending request');
 check((await action('feedback',{kind:'app',rating:0,text:'No rating'},'qa-tourist')).status===400,'app feedback requires a rating');
 const sent=await action('feedback',{kind:'help',rating:0,text:'QA tourist support request'},'qa-tourist','tourist');const ticket=sent.state.feedback[0];
 check(sent.status===200&&ticket.status==='open'&&ticket.author==='City Guide','tourist support request is saved with its author and status');
 check(!(await request('/api/state?surface=tourist','qa-partner')).feedback.some(f=>f.id===ticket.id),'support requests are private to their sender');
 check((await request('/api/state?surface=admin')).feedback.some(f=>f.id===ticket.id),'administrator sees tourist support requests');
 check((await action('feedbackStatus',{id:ticket.id,version:1,status:'resolved',reply:'Unauthorized'},'qa-tourist')).status===403,'tourists cannot reply as support staff');
 const resolved=await action('feedbackStatus',{id:ticket.id,version:1,status:'resolved',reply:'QA administrator reply'});
 const senderTicket=(await request('/api/state?surface=tourist','qa-tourist')).feedback.find(f=>f.id===ticket.id);
 check(resolved.status===200&&senderTicket.status==='resolved'&&senderTicket.reply==='QA administrator reply','support reply and resolution reach the request sender');
 check((await action('feedbackStatus',{id:ticket.id,version:1,status:'open',reply:''})).status===409,'stale support edits are rejected');
 const editProfile=await action('profile',{name:'QA partner',phone:'',language:'tr',homeAddress:'',role:'admin'},'qa-partner');check(editProfile.state.user.role==='partner'&&editProfile.state.user.language==='tr','profile language persists without role escalation');
 const touristProfile=await action('profile',{name:'QA tourist',phone:'',language:'en',homeAddress:'İstanbul',role:'partner'},'qa-tourist','tourist');
 check(touristProfile.state.user.role==='tourist'&&touristProfile.state.user.homeAddress==='İstanbul','tourist profile cannot self-assign the business role');
 const form=new FormData();form.set('file',new File([await readFile('public/icon-192.png')],'qa.png',{type:'image/png'}));
 const encoded=new Request('http://local.test/api/upload',{method:'POST',body:form});const bytes=await encoded.arrayBuffer();const contentType=encoded.headers.get('content-type');
 const up=await mf.dispatchFetch('http://local.test/api/upload',{method:'POST',headers:{...headers('qa-owner'),'content-type':contentType},body:bytes});const upload=await up.json();check(up.status===200&&upload.url.startsWith('/api/media/'),'uploaded photo is stored in R2');
 const blockedUpload=await mf.dispatchFetch('http://local.test/api/upload',{method:'POST',headers:{...headers('qa-tourist'),'content-type':contentType},body:bytes});check(blockedUpload.status===403,'tourists cannot upload business photos');
 const forbiddenPhoto=await mf.dispatchFetch('http://local.test'+upload.url,{headers:headers('qa-partner')});check(forbiddenPhoto.status===403,'unpublished uploads are private');
 check((await action('saveVenue',{...saved,image:upload.url,gallery:[upload.url]})).status===200,'uploaded image attaches to a listing');
 const publicPhoto=await mf.dispatchFetch('http://local.test'+upload.url,{headers:headers('qa-tourist')});check(publicPhoto.status===200&&publicPhoto.headers.get('content-type')==='image/png','published listing image is available to signed-in tourists');
 check((await request('/api/weather?lat=999&lon=0','qa-tourist')).status===400,'invalid weather coordinates are rejected before external requests');
 check((await request('/api/weather?lat=41&lon=29',null)).status===401,'forecast endpoint requires authentication');
 for(const [area,who] of [['admin','qa-owner'],['partner','qa-partner'],['tourist','qa-tourist']]){
  const html=await mf.dispatchFetch('http://local.test/'+area,{headers:headers(who)});const body=await html.text();
  check(html.status===200&&body.includes('City Guide')&&!body.includes('Internal Server Error'),'server renders the '+area+' area');
 }
 const rootResponse=await mf.dispatchFetch('http://local.test/',{headers:headers('qa-owner'),redirect:'manual'});check([302,303,307,308].includes(rootResponse.status)&&rootResponse.headers.get('location')==='/tourist','root sends administrators to the client home');
 const blocked=await mf.dispatchFetch('http://local.test/admin',{headers:headers('qa-tourist'),redirect:'manual'});check([302,303,307,308].includes(blocked.status)&&blocked.headers.get('location')==='/tourist','protected administrator page redirects a tourist');
 const anon=await mf.dispatchFetch('http://local.test/tourist',{redirect:'manual'});check([302,303,307,308].includes(anon.status)&&anon.headers.get('location').startsWith('/signin-with-chatgpt'),'tourist page requires a signed-in user');
 console.log(JSON.stringify({passed:checks,scope:'compiled Worker + in-memory D1/R2',browserQA:false}));
}finally{await mf.dispose()}
