import {type Localized} from './model';
export type Phase={number:string;status:'ready'|'next'|'later';title:Localized;items:Localized;acceptance:Localized};
export const phases:Phase[]=[
{number:'01',status:'ready',title:{ru:'Основа и рабочий кабинет',tr:'Temel altyapı ve yönetim paneli',en:'Foundation & workspace'},items:{ru:'RU / TR / EN, адаптивный интерфейс, общая база, каталог, редактирование заведений и загрузка фотографий.',tr:'RU / TR / EN, mobil uyumlu arayüz, ortak veri tabanı, katalog, işletme düzenleme ve fotoğraf yükleme.',en:'RU / TR / EN, responsive interface, shared database, catalog, place editing and photo uploads.'},acceptance:{ru:'Карточка сохраняется после перезагрузки и видна в каталоге после публикации.',tr:'Kayıt yenileme sonrası korunur ve yayınlandıktan sonra katalogda görünür.',en:'A listing survives refresh and appears in the catalog after publication.'}},
{number:'02',status:'next',title:{ru:'Подключение настоящих партнёров',tr:'Gerçek iş ortaklarının katılımı',en:'Real partner onboarding'},items:{ru:'Отдельные аккаунты, приглашения, одобрение бизнеса, роли владельца, партнёра и инвестора, почтовые подтверждения.',tr:'Ayrı hesaplar, davetler, işletme onayı, yönetici, iş ortağı ve yatırımcı rolleri, e-posta doğrulaması.',en:'Separate accounts, invitations, business approval, owner, partner and investor roles, email verification.'},acceptance:{ru:'Каждый партнёр видит только свои служебные данные. Инвестор получает доступ только к просмотру.',tr:'Her ortak yalnızca kendi özel verilerini görür. Yatırımcı salt okunur erişim alır.',en:'Each partner sees only their private records. The investor has read-only access.'}},
{number:'03',status:'next',title:{ru:'Полные сценарии бронирования',tr:'Eksiksiz rezervasyon akışları',en:'Complete booking workflows'},items:{ru:'Столики, автопарк, услуги со специалистами, мероприятия и номера отелей. Занятость, отмены, уведомления. Базовые тестовые заявки уже работают.',tr:'Masalar, araç filosu, uzman randevuları, etkinlikler ve otel odaları. Müsaitlik, iptaller ve bildirimler. Temel test rezervasyonları hazır.',en:'Tables, vehicle inventory, staff appointments, events and hotel rooms. Availability, cancellations and notifications. Basic test bookings are ready.'},acceptance:{ru:'Два гостя не могут забронировать последнюю единицу одновременно.',tr:'İki misafir son müsait kaynağı aynı anda ayıramaz.',en:'Two guests cannot book the last available resource simultaneously.'}},
{number:'04',status:'next',title:{ru:'Гид для гостей',tr:'Misafirler için şehir rehberi',en:'The guest city guide'},items:{ru:'Все категории, карта с несколькими метками, расширенные фильтры, история, избранное, путь домой, погода, курсы и поиск Ask Me.',tr:'Tüm kategoriler, çok işaretli harita, gelişmiş filtreler, geçmiş, favoriler, eve dönüş, hava, kurlar ve Ask Me araması.',en:'All categories, multi-marker map, advanced filters, history, favorites, way home, weather, exchange and Ask Me search.'},acceptance:{ru:'Гость находит место и отправляет заявку с телефона на выбранном языке.',tr:'Misafir telefonundan seçtiği dilde mekan bulup talep gönderir.',en:'A guest finds a place and submits a request on mobile in their language.'}},
{number:'05',status:'later',title:{ru:'Отзывы, акции и лояльность',tr:'Yorumlar, kampanyalar ve sadakat',en:'Reviews, offers & loyalty'},items:{ru:'Проверенные отзывы, ответы бизнеса, модерация, рекламные баннеры, промокоды, правила баллов. Базовые отзывы и скидки уже доступны.',tr:'Doğrulanmış yorumlar, işletme yanıtları, moderasyon, reklamlar, promosyon kodları ve puan kuralları. Temel yorum ve indirimler hazır.',en:'Verified reviews, business replies, moderation, banners, promo codes and reward rules. Basic reviews and discounts are ready.'},acceptance:{ru:'Скидки рассчитываются на сервере, баллы имеют историю начислений и списаний.',tr:'İndirimler sunucuda hesaplanır; puanların kazanım ve harcama geçmişi vardır.',en:'Discounts are calculated server-side; points have an earning and spending ledger.'}},
{number:'06',status:'later',title:{ru:'Платежи и выплаты',tr:'Ödemeler ve hak edişler',en:'Payments & payouts'},items:{ru:'Выбор бизнес-модели, подключение iyzico, токены карт, подтверждения оплаты, возвраты и выплаты партнёрам.',tr:'İş modelinin seçimi, iyzico bağlantısı, kart tokenları, ödeme doğrulaması, iadeler ve iş ortağı ödemeleri.',en:'Business model, iyzico integration, card tokens, payment confirmations, refunds and partner payouts.'},acceptance:{ru:'Оплата подтверждается провайдером; повторный запрос не приводит к двойному списанию.',tr:'Ödeme sağlayıcı tarafından doğrulanır; tekrar istek çift tahsilata yol açmaz.',en:'Payment is verified by the provider; retries cannot charge twice.'}},
{number:'07',status:'later',title:{ru:'Публичный запуск и новые города',tr:'Herkese açık lansman ve yeni şehirler',en:'Public launch & more cities'},items:{ru:'Проверка KVKK, резервные копии и восстановление, мониторинг, лимиты расходов, тесты мобильных устройств. Затем магазины приложений.',tr:'KVKK incelemesi, yedekleme ve kurtarma, izleme, harcama sınırları ve mobil testler. Ardından uygulama mağazaları.',en:'KVKK review, backup and recovery, monitoring, spending limits and mobile tests. App stores follow.'},acceptance:{ru:'Проверены доступы и восстановление данных; новый город добавляется без переделки приложения.',tr:'Erişim ve veri kurtarma doğrulanır; yeni şehir uygulama değiştirilmeden eklenir.',en:'Access and recovery are verified; another city can be added without rebuilding the app.'}}
];
