import {sqliteTable,text,integer,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const meta=sqliteTable('cg_meta',{key:text('key').primaryKey(),value:text('value').notNull()});
export const users=sqliteTable('cg_users',{id:text('id').primaryKey(),email:text('email').notNull(),payload:text('payload').notNull(),createdAt:text('created_at').notNull()});
export const venues=sqliteTable('cg_venues',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),status:text('status').notNull(),city:text('city').notNull(),category:text('category').notNull(),isDemo:integer('is_demo').notNull().default(0),version:integer('version').notNull().default(1),payload:text('payload').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_venues_owner').on(t.ownerId),index('idx_venues_status_city').on(t.status,t.city)]);
export const bookings=sqliteTable('cg_bookings',{id:text('id').primaryKey(),userId:text('user_id').notNull(),venueId:text('venue_id').notNull().references(()=>venues.id),date:text('date').notNull(),endDate:text('end_date').notNull(),time:text('time').notNull(),guests:integer('guests').notNull(),status:text('status').notNull(),payload:text('payload').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_bookings_user').on(t.userId),index('idx_bookings_availability').on(t.venueId,t.date,t.status)]);
export const favorites=sqliteTable('cg_favorites',{userId:text('user_id').notNull(),venueId:text('venue_id').notNull().references(()=>venues.id)},t=>[primaryKey({columns:[t.userId,t.venueId]})]);
export const reviews=sqliteTable('cg_reviews',{id:text('id').primaryKey(),userId:text('user_id').notNull(),venueId:text('venue_id').notNull().references(()=>venues.id),bookingId:text('booking_id').notNull().unique(),payload:text('payload').notNull(),status:text('status').notNull().default('published'),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('idx_reviews_venue').on(t.venueId)]);
export const feedback=sqliteTable('cg_feedback',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),payload:text('payload').notNull(),status:text('status').notNull().default('open'),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('idx_feedback_user').on(t.userId)]);
export const uploads=sqliteTable('cg_uploads',{id:text('id').primaryKey(),userId:text('user_id').notNull(),key:text('key').notNull(),contentType:text('content_type').notNull(),createdAt:text('created_at').notNull()});
